workflows:
  android-workflow:
    name: "Build Debug APK"
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.polarize"
    scripts:
      - name: "Give gradlew execute permission"
        script: |
          chmod +x ./gradlew
      - name: "Build Debug APK"
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
